### ISSUE TITLE
Duplicating the water body makes one not work.

### ISSUE THREAD

**Issue by HeadMonitor** [MemoryLeakHub/Water2D-Unity#1]
I have found an issue with this project. Although very helpful it seems like the water body will not work properly if duplicated. Any chance I can get some guidance for this fix? Thanks a lot!

**Comment by rdm144** [comment]
I found a work around by editing WaterSpring.cs line 16 and removing the "static" keyword from the spriteShapeController variable, and then reinitializing my waves count on the water shape controller. This way, the springs from the duplicated water shouldn't use the sprite shape controller from the original body of water.
