### ISSUE TITLE
The water doesn't work in a Build

### ISSUE THREAD

**Issue by EduTKN** [MemoryLeakHub/Water2D-Unity#2]
I have noticed that when playing in the editor and in the game screen the project works fine and the water interacts with the player/box. however when making a build of the FinalPreviewScene the scrip stops working and the springs don't react to the player anymore... does anyone know a way to fix it?

**Comment by jirapher** [comment]
Bump? I really like this water but for the life of me can't figure out why it's not working outside the editor. 

Update: I changed a lot of things but what finally worked was removing the OnValidate call (moved the coroutine to start).
